package main

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
)

func main() {
	ctx := context.Background()

	conn, err := pgx.Connect(ctx, os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(ctx)

	_, err = conn.Exec(ctx, `
		create temporary table users (
			id int primary key generated by default as identity,
			name text not null,
			email text not null
		)`)
	if err != nil {
		log.Fatal(err)
	}

	batch := &pgx.Batch{}
	batch.Queue("insert into users (name, email) values ($1, $2)", "Matthew", "matthew@example.com")
	batch.Queue("insert into users (name, email) values ($1, $2)", "Mark", "mark@example.com")
	err = conn.SendBatch(ctx, batch).Close()
	if err != nil {
		log.Fatal(err)
	}

	var n int32
	err = conn.QueryRow(ctx, "select count(*) from users").Scan(&n)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(n) // => 2
}
